name: Build binaries & add as release assets

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            executable: opshin-linux
          - os: macos-latest
            executable: opshin-macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pex

    - name: Build Binary with Pex
      run: |
        pip install ./  # Ensure your package and its dependencies are installed
        pip freeze > requirements.txt
        pex -r requirements.txt setuptools -c opshin -o ./dist/${{ matrix.executable }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/${{ matrix.executable }}
        asset_name: ${{ matrix.executable }}
        asset_content_type: application/octet-stream
